### PR TITLE
#793 - Updating SDK, Tools, and Support Libraries to API 25

### LINKED ISSUE #793: Update To Android 7.1.1 / API 25
The [final Developer Preview for Android API 25 (aka 7.1.1)](http://android-developers.blogspot.com/2016/11/final-update-to-android-7-1-developer-preview.html) was released on 22-Nov-2016 in advance of it's official release and software updates being pushed to Nexus / Pixel devices in early December 2016.  Updating now will give more time to test the app in development with this SDK and Support Libraries beforehand.

/cc @sarahlensing @ecgreb

### PR DESCRIPTION
**Pull request by bleege**
### Overview

Resolves #793 

### Proposed Changes

Updates SDK, Tools, and Support Libraries to API 25

/cc @sarahlensing @ecgreb

### CODE REVIEW

**Comment by ecgreb** [comment]
Hey @bleege thanks for the pull request!

It looks like `circle.yml` also needs to be updated to install version 25 of the platform and build tools.

https://github.com/mapzen/eraser-map/blob/master/circle.yml#L13-L14

**Comment by bleege** [comment]
Good catch @ecgreb!  I've updated the circle.yml file so the next step is to wait to see if Circle CI is happy with it.

**Comment by bleege** [comment]
Just following up on the build from Friday night and noting that the updated `circle.yml` file did the trick.  The build failure now is due to the build script not having an access key to AWS so that the app could be deployed.

```
Total time: 3 mins 2.176 secs
app/build/outputs/apk/app-dev-debug.apk -> s3://android.mapzen.com/erasermap-development/pull/794-1859.apk  [1 of 1]

 18577707 of 18577707   100% in    1s    12.24 MB/s  done
ERROR: S3 error: 403 (InvalidAccessKeyId): The AWS Access Key Id you provided does not exist in our records.

scripts/deploy.sh returned exit code 1

Action failed: scripts/deploy.sh
```

**Comment by ecgreb** [comment]
This appears to be an issue with Circle CI. Building a fork pull request does not give access to the AWS credentials which are stored in secure environment variables configured via Circle's web UI. Building the same commits on a non-fork branch fixed the build.

I created a new issue here to track the problem building fork pull requests: https://github.com/mapzen/eraser-map/issues/797

Otherwise changes look good so I'm going to merge. Thanks @bleege!

**Pull request merged**
