### PR TITLE
Handle implicit intents

### LINKED ISSUE #545: Handle implicit intents
Both geo and map intents.

### PR DESCRIPTION
**Pull request by ecgreb**
Handle implicit geo and map intents generated by other applications.

* Updates AndroidManifest.xml to receive geo and maps intents
* Log incoming intent and forward to MainActivity
* Perform input validation and pass valid query to parser
* Adds logic to parse query string
* Populate current search term with IntentQueryParser result
* Execute search on incoming query string
* Set map position prior to search based on focus point if available
* Handle implicit intent even if app is already running in background

Closes #545

### CODE REVIEW

**Comment by sarahlensing** [comment]
Looks good! A couple issues I'm seeing- it looks like we arent decoding the query and it also seems like we aren't executing a search if the app has already been launched and we receive an implicit intent. It could be because the MainActivity is not setup to handle intents, only the InitActivity is. See below:
screenshot_20160520-154752
screenshot_20160520-154819

**Comment by ecgreb** [comment]
`Uri#getQuery()` _claims_ to decode the query string but that doesn't mean I trust it. What does the intent data look like when `InitActivity` logs it to the console? Also what app are you using to generate the intents?

https://developer.android.com/reference/android/net/Uri.html#getQuery()

I am invoking `presenter.onIntentQueryReceived(intent?.data?.query)` from `MainActivity#onNewIntent(Intent)` specifically to handle the case where the app is already running in the background. I wonder if this is another issue specific to Samsung devices (similar to vanishing API keys) because of the way TouchWiz handles background apps. On the Robin implicit intents are handled correctly when app is already open.

**Comment by sarahlensing** [comment]
When it's logged its `Incoming implicit intent: geo:0,0?q=Pier+97` however `data.toString()` is `geo:0,0?q=Pier+97` :/

I'm using Google Calendar to generate the intent.

It could definitely be an issue related to that. As a simple test, I set a breakpoint in `onNewIntent` and found it was never called. Then I added the intent filters to `MainActivity` and rebuilt and saw that `onNewIntent` in `MainActivity` was invoked however this breaks the case where the app isn't running because the ApiKeys are initialized/configured in InitActivity. There might be another way to handle this but adding the intent filters to `MainActivity` seems to have fixed what I saw. If we initialize the ApiKeys in the init block of `ApiKeys` and remove it from `InitActivity` it would fix both issues. Of course, we need to make sure this still works on the Robin...

**Comment by ecgreb** [comment]
Thanks for the additional info and debugging. Its very strange indeed that `onNewIntent(...)` doesn't even get called.

**Comment by ecgreb** [comment]
@sarahlensing both issues have been addressed in subsequent commits. Thanks for your help tracking them down!

**Comment by sarahlensing** [comment]
@ecgreb The changes look good- merging!

**Pull request merged**
