### PR TITLE
Route preview zooms to fit bounds of the route

### PR DESCRIPTION
**Pull request by blair1618**
When previewing a route, this will calculate the lon/lat bounding box of the route geometry and move/zoom the map to show the entire route, taking into account the current screen dimensions, with a configurable amount of padding. If no route is found for a search, the preview will now zoom to fit the start and end pins. 

This also adds a utility class for an axis-aligned bounding box - might be useful in other places.

### CODE REVIEW

**Comment by tallytalwar** [comment]
Looks like, its does not zoom out the map when no route is found (in all the cases).

Working repro:
Search/RouteTo: Paris, France

Not Working Repro:
Search/RouteTo: Auckland, NZ

**Comment by blair1618** [comment]
Aw dang, the bounding box is probably wrong in some way when the "route" crosses the international dateline. I'll look into that.

**Comment by tallytalwar** [comment]
yeah, I think you will have to wrap the view somehow.

**Comment by blair1618** [comment]
Hm ok, so all of the logic in this PR is handling these cases correctly. The unusual behavior actually comes from a bit of code in tangram-es that constrains the view from extending beyond the edges of the world. 

When you try to set a view parameter that would result in seeing area beyond the edge of the world, tangram-es stops the change completely and remains at the previous value. In this case, when we try to zoom out and see both New York and Auckland, the resulting zoom level would make visible some area beyond the edge of the world, so the map remains at the previous zoom value (probably 16). What I would expect as a developer and as a user would be for tangram-es to take the closest possible value to the input, rather than doing nothing. 

I can file an issue for tangram-es to improve this behavior, but for now it might be best to not attempt a route preview when no route is found.

**Comment by tallytalwar** [comment]
Yes mostly thats the case.

Another case which I tried is "Delhi, India". Both "New York" and "Delhi" do fit the tangram view at zoom:1, but route preview fails to show this.

screenshot_2016-02-09-19-02-18

**Comment by blair1618** [comment]
For the case of Delhi, the app is still trying to zoom out farther than tangram-es will allow; the route preview zooms to fit a box containing both endpoints plus 35% padding.

**Comment by tallytalwar** [comment]
Yup totally.

I agree on your suggestion of handing this on tangram-es. This pr looks
good to me with respect to bounding box logic.

**Comment by mjcunningham** [comment]
Is the behavior in this PR that if no route is found you cant get into the preview view?

**Comment by blair1618** [comment]
With the changes in this PR, when no route is found the "preview" will move
and zoom to show the start and end locations. There are some exceptional
cases that Varum pointed out where the zoom will not be correct for
extremely long (read, intercontinental) routes.

**Comment by tallytalwar** [comment]
@mjcunningham Nopes, it only takes care of zoom out to fit the route (if one is found), and to fit the start and end pins (if no route is found).

However on checking other mapping apps, when no route is found, they just show the last map view without trying to fit the start and end markers in the same map view (not possible all the time, as discussed above)

**Comment by mjcunningham** [comment]
:+1: lets try this and see how it feels.

**Comment by blair1618** [comment]
The last commit addresses these uncommon cases where tangram can't set the desired zoom - instead the map will just stay at the current location.

**Comment by tallytalwar** [comment]
This looks good to me.

**Pull request merged**
