### PR TITLE
add data sources and update added data

### PR DESCRIPTION
**Pull request by tallytalwar**
This fixes things on eraser-map app side.

However there is regression coming from a recent change to tangram-es core library. I am working on that fix, and should be good by tonight.

### CODE REVIEW

**Comment by tallytalwar** [comment]
This PR along with https://github.com/tangrams/tangram-es/pull/373 on tangram-es should fix all client data.

**Comment by tallytalwar** [comment]
Putting on a brief hold before I fix route Icon.

**Comment by tallytalwar** [comment]
Route_icon back in and using latest MapData API changes.

**Comment by ecgreb** [comment]
Fixes https://github.com/mapzen/eraser-map/issues/80

**Pull request merged**
