### PR TITLE
fixes bug involving lack of gradle.properties

### PR DESCRIPTION
**Pull request by kingofirony**
- Fixes bug involving crash if buildconfig is not available.

### CODE REVIEW

**Comment by ecgreb** [comment]
Looks like this one was on me. Nice catch :)

**Comment by ecgreb** [comment]
cc @tallytalwar @blair1618

**Comment by tallytalwar** [comment]
will give this a shot before the meeting today.

**Comment by tallytalwar** [comment]
This works ... Thanks for the fix :D.

**Pull request merged**
